version: "3.8"

services:
  app:
    image: mytsyaispat/kameleoon-trial-task:v1
    container_name: application
    environment:
      DB_PASSWORD: password
      DB_USER: sa
      DB_DATABASE: kameleoon_db
    ports:
      - "8080:8080"